/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlatformsRouteImport } from './routes/admin.platforms'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSocialRouteImport } from './routes/admin.social'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminProductIdRouteImport } from './routes/admin.product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformsRoute = AdminPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product/$id': typeof AdminProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/platforms'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/social'
    | '/product/$slug'
    | '/admin/'
    | '/admin/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/platforms'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/social'
    | '/product/$slug'
    | '/admin'
    | '/admin/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/terms'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/platforms'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/social'
    | '/product/$slug'
    | '/admin/'
    | '/admin/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platforms': {
      id: '/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminPlatformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlatformsRoute: typeof AdminPlatformsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlatformsRoute: AdminPlatformsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductIdRoute: AdminProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
